apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2019-09-26T22:00:08Z"
    generation: 1
    labels:
      run: hello-node
    name: hello-node
    namespace: default
    resourceVersion: "5781"
    selfLink: /apis/apps/v1/namespaces/default/deployments/hello-node
    uid: 735b7e82-8803-4a57-8629-1e6812fc16bd
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: hello-node
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: hello-node
      spec:
        containers:
        - image: hello-node:v1
          imagePullPolicy: Never
          name: hello-node
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2019-09-26T22:00:08Z"
      lastUpdateTime: "2019-09-26T22:00:08Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2019-09-26T22:10:09Z"
      lastUpdateTime: "2019-09-26T22:10:09Z"
      message: ReplicaSet "hello-node-55fd8585c" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2019-09-27T19:16:52Z"
    generation: 1
    labels:
      run: load-generator
    name: load-generator
    namespace: default
    resourceVersion: "99295"
    selfLink: /apis/apps/v1/namespaces/default/deployments/load-generator
    uid: 64f7216e-7c2d-445b-b03e-0dbada37a353
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: load-generator
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: load-generator
      spec:
        containers:
        - args:
          - /bin/sh
          image: busybox
          imagePullPolicy: Always
          name: load-generator
          resources: {}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2019-09-27T19:16:58Z"
      lastUpdateTime: "2019-09-27T19:16:58Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2019-09-27T19:16:52Z"
      lastUpdateTime: "2019-09-27T19:16:58Z"
      message: ReplicaSet "load-generator-5fb4fb465b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2019-09-27T19:22:39Z"
    generation: 1
    labels:
      run: load-generator3
    name: load-generator3
    namespace: default
    resourceVersion: "100161"
    selfLink: /apis/apps/v1/namespaces/default/deployments/load-generator3
    uid: 5f1b8e26-09cd-4e08-a476-9ead3625cc1b
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: load-generator3
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: load-generator3
      spec:
        containers:
        - args:
          - /bin/sh
          image: busybox
          imagePullPolicy: Always
          name: load-generator3
          resources: {}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2019-09-27T19:22:43Z"
      lastUpdateTime: "2019-09-27T19:22:49Z"
      message: ReplicaSet "load-generator3-644f459dc8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2019-09-27T19:26:41Z"
      lastUpdateTime: "2019-09-27T19:26:41Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2019-09-27T19:39:47Z"
    generation: 1
    labels:
      run: load-generator4
    name: load-generator4
    namespace: default
    resourceVersion: "102459"
    selfLink: /apis/apps/v1/namespaces/default/deployments/load-generator4
    uid: 006093d8-1c51-4e65-aa84-7654e4a8f6cb
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: load-generator4
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: load-generator4
      spec:
        containers:
        - args:
          - /bin/sh
          image: busybox
          imagePullPolicy: Always
          name: load-generator4
          resources: {}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2019-09-27T19:39:47Z"
      lastUpdateTime: "2019-09-27T19:39:52Z"
      message: ReplicaSet "load-generator4-764cb5474d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2019-09-27T19:51:10Z"
      lastUpdateTime: "2019-09-27T19:51:10Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2019-09-27T19:54:05Z"
    generation: 1
    labels:
      run: load-generator5
    name: load-generator5
    namespace: default
    resourceVersion: "102798"
    selfLink: /apis/apps/v1/namespaces/default/deployments/load-generator5
    uid: 629db6a6-4dea-42e7-905e-ce336f7a1a8f
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: load-generator5
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: load-generator5
      spec:
        containers:
        - args:
          - /bin/sh
          image: busybox
          imagePullPolicy: Always
          name: load-generator5
          resources: {}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2019-09-27T19:54:11Z"
      lastUpdateTime: "2019-09-27T19:54:11Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2019-09-27T19:54:05Z"
      lastUpdateTime: "2019-09-27T19:54:11Z"
      message: ReplicaSet "load-generator5-5f8d894fd6" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2019-09-27T19:58:34Z"
    generation: 13
    labels:
      run: py-fs
    name: py-fs
    namespace: default
    resourceVersion: "110870"
    selfLink: /apis/apps/v1/namespaces/default/deployments/py-fs
    uid: af7233de-c54c-4f08-99bc-5159a431b28b
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        run: py-fs
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: py-fs
      spec:
        containers:
        - image: rogeriosilvarocha/pyfs:latest
          imagePullPolicy: Never
          name: py-fs
          ports:
          - containerPort: 5000
            protocol: TCP
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2019-09-27T19:58:34Z"
      lastUpdateTime: "2019-09-27T19:58:39Z"
      message: ReplicaSet "py-fs-5876cb7669" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2019-09-27T21:36:12Z"
      lastUpdateTime: "2019-09-27T21:36:12Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 13
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2019-09-26T22:11:15Z"
    name: hello
    namespace: default
    resourceVersion: "5896"
    selfLink: /api/v1/namespaces/default/services/hello
    uid: 818219fd-4e07-4139-8e5b-63834946a912
  spec:
    clusterIP: 10.109.165.26
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 30002
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hello
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2019-09-26T21:17:13Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "1243"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: 3a0c901b-8ca8-4a78-9202-a8591c43da8a
  spec:
    clusterIP: 10.96.0.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"microapi","namespace":"default"},"spec":{"ports":[{"nodePort":30001,"port":3000}],"selector":{"app":"microapi"},"type":"NodePort"}}
    creationTimestamp: "2019-09-26T21:22:04Z"
    name: microapi
    namespace: default
    resourceVersion: "1764"
    selfLink: /api/v1/namespaces/default/services/microapi
    uid: 56bcb4fa-6ef1-450f-9ff7-3b614d3eae24
  spec:
    clusterIP: 10.105.175.172
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 30001
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: microapi
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2019-09-27T19:58:34Z"
    name: py-fs
    namespace: default
    resourceVersion: "103183"
    selfLink: /api/v1/namespaces/default/services/py-fs
    uid: a10bfcb2-3ccd-48b5-a1be-f4738d6da681
  spec:
    clusterIP: 10.108.28.91
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      run: py-fs
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  data:
    ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1Ea3lOakl4TURZeU4xb1hEVEk1TURreU16SXhNRFl5TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTm1yCitFTUlQM3JScHhVQzl0WHdkRlViVEp0RkNPcGZmRG9IUjNRU0lES0tTQ05iTXNHdW5oVlhyOG1tYnRocytMWXUKOFlSazF4ZnZsTzhHZjg3VzRQWXhVOWY0VWdDZ040TlN4UWo4b0dMc1MrRU02K2d5cEtNdlVYRm5yanJLL3RwaApvcEhzYkZPeWdLWGJUT2hFcnZFMWpZT201bFpUNWR6dDZuQkY0a0drYmUxaEt5cWZwQTVjWWNCeGUyODF5UVFpClN5YVZwSm85Mmx4RzNtVXpCc1JHZXl4TndodDgrb0RvWmlxRm9BS1JhMC9aZ1MyUFRsSHZEYkFVOERUMS8zZzkKaXJJVmYvMXpYS2NFc1RnNGpWY1FJSGZ6WmZZYk5kaDhDS3hSdWgrZkUvSEtaeHVZbVpPcTRwWjlXWkMwOFc2TgozQ0FEajNwTXZJQUlqK01FZDVVQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMUy9GNHpqaEJIN3VlZG9UTWFGeTBCWWVNb1oKK0d1eXFHdjVsWk9RYkdSZVdmTGhOOFVTTDBKOVNMejExOVJmbTBwcEhPV1BaQ2IwWGdpek5CdmJmVlJUVndLbwpHMmpxSXVzVEVENG13MG1KUFBUb2RTT052eTFLTTRpRnFQOSt5NjZYeXBaYjZkU3ZVRllmazQvbkwzNlVXL0o4Cmx5K1l1V2g0N1hJVmExaW9TNzAxQjJITnV3bDRINEV2Q29HZ3c2cG5mN0thdldqenF1K3BiWElVVnFhcUk4SVUKcmtPV3RFWStWdmp4YkNXM2VQMGxmSmhLNzBVWENwa1I3bFNqYk5XSktJL0E2Q3hkRlRmZ2hXYWpBOU5LVVlXNgpPclBMMnh1R1o2dEVEWVZ0V0VTYjhaLzJ3YzNEQy8rZzRyQ3lGUk5ROEhjR1ZzRXV6M2E1dVYwUlVuND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    namespace: ZGVmYXVsdA==
    token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltWTNTRzFqU2tRM2EyZE5PVEZJTFVKa0xXTm1WVEZzV1ZkblVUWkJWM1ZJWVZOUGRHaGFhSEpUZDFFaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbVJsWm1GMWJIUXRkRzlyWlc0dGFqbHJkM1lpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pWkdWbVlYVnNkQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJamt4TmpBd05EUTJMV0U1T0RndE5HUTBPQzFoTVRKbUxUazFZemRtWldVd01XVmlZU0lzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwa1pXWmhkV3gwT21SbFptRjFiSFFpZlEub3piSnZURlBqcUdEZ3ZkamdVUTNjOUlUZVhkUlBHY1pBTHdnbksyeV9yYU5VZjc1NlJYMDR6RWppbG42ZHhWX25nTnVWbV9EU1h3RFRBXzZLVE1WdjRtVWlpQXpHZzVuX1k4TTU4QWZRUGpYQUQwMEtxdkxRWWtlMi1Cbm1RUkI0NHg3azY1UEMxaEdCQ05NLXk3cXF5NHJFUnlGLWVKOXk4blVJQ0NjZVVZVmZSbFZUZ1ZHQ2VNRGN0WEo5UTNqckk2ZVdWYlMwaGQ5LVlOTk1GNUptb05IaUdWbU4wYldEMkwtU3lwZmlRTmlES3Frd3FGYUVpUGRtVUNFT1J5bVRNSEQzS2dRZWpQU2RPRE5TSlFlT0hxRmFLNG1jMUx1cjNmLXZQMUVPeVBTVE5NWHAwQUttdWlfczlTRmRUMWx2T1RPVnNLcHFtYXNaWEI0N0xUOENn
  kind: Secret
  metadata:
    annotations:
      kubernetes.io/service-account.name: default
      kubernetes.io/service-account.uid: 91600446-a988-4d48-a12f-95c7fee01eba
    creationTimestamp: "2019-09-26T21:07:50Z"
    name: default-token-j9kwv
    namespace: default
    resourceVersion: "356"
    selfLink: /api/v1/namespaces/default/secrets/default-token-j9kwv
    uid: a533d8c8-5d46-4f7e-89c7-b20706f813e9
  type: kubernetes.io/service-account-token
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
