FROM python:3.7.4-slim
COPY . /app
WORKDIR /app

ARG SERVICE_VERSION
ARG SERVICE_SOURCE_COMMIT_ID
ARG SERVICE_SOURCE_MESSAGE
ARG SERVICE_SOURCE_BRANCH
ARG SERVICE_VV
ARG SERVICE_REQUESTED_FOR
ARG SERVICE_NAME

ENV SERVICE_NAME=$SERVICE_NAME
ENV SERVICE_VERSION=$SERVICE_VERSION
ENV SERVICE_NAME=$SERVICE_NAME
ENV SERVICE_SOURCE_COMMIT_ID=$SERVICE_SOURCE_COMMIT_ID
ENV SERVICE_SOURCE_MESSAGE=$SERVICE_SOURCE_MESSAGE
ENV SERVICE_SOURCE_BRANCH=$SERVICE_SOURCE_BRANCH
ENV SERVICE_VV=$SERVICE_VV
ENV SERVICE_REQUESTED_FOR=$SERVICE_REQUESTED_FOR

RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["waitress_server.py"]