apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: py-fs
  name: py-fs-lb
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: py-fs
  type: LoadBalancer
status:
  loadBalancer: {}
