apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: py-fs
  name: py-fs
spec:
  replicas: 1
  selector:
    matchLabels:
      run: py-fs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: py-fs
    spec:
      containers:
      - image: rogeriosilvarocha/pyfs:latest
        imagePullPolicy: Never
        name: py-fs
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: fs-storage
          mountPath: /data/store
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      volumes:
        - name: fs-storage
        persistentVolumeClaim:
          claimName: task-pv-storage
status: {} 
